name: deploy the backend

on:
  push:
    branches: [main]

jobs:   # virtual computer 
  build:
    runs-on: ubuntu-latest  ## github  give the tempprary machine ubuntu machine 
    steps:
      - name: Check out the code   # take code from the repo put into the virtual computer 
        uses: actions/checkout@v2

      - name: Docker login           # here is the docker login 
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push    # docker image build and push on the docker hub 
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Docker/Dockerfile.backend
          push: true
          tags: yuvi062006/week-27-2-backend:${{ github.sha }}
      - run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" &> ~/ssh_key
          mkdir -p /home/runner/.ssh   
          chmod 600 /home/runner/ssh_key
          ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@3.109.2.89 -t "sudo docker stop user_backend || true 
          sudo docker rm user_backend || true 
          sudo docker run --name user_backend -d -p 8080:8080 -e DATABASE_URL='${{ secrets.DATABASE_URL }}' yuvi062006/week-27-2-backend:${{ github.sha }}"


